version: '3'

volumes:
    database:
    database-logs:
    python-logs:

networks:
    legendhub:

services:
    mysql:
        build:
            context: ./mysql
        environment:
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        networks:
            - legendhub
        volumes:
            - database:/var/lib/mysql
            - database-logs:/var/log
        tty: true
        restart: always
    www:
        build:
            context: ./www
        depends_on:
            - mysql
        ports:
            - "${EXTERNAL_PORT}:${PORT}"
        environment:
            - PORT=${PORT}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_HOST=mysql
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - GITHUB_TOKEN=${GITHUB_TOKEN}
            - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
            - RECAPTCHA_SECRET=${RECAPTCHA_SECRET}
        networks:
            - legendhub
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 20s
        restart: always
    python:
        build:
            context: ./python
        depends_on:
            - mysql
        environment:
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_HOST=mysql
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        networks:
            - legendhub
        volumes:
            - python-logs:/var/log
        restart: always
